### ISSUE TITLE
Pre-Req Step Role Assignment Script Fails

### ISSUE THREAD

**Issue by simone-bennett** [Azure/Enterprise-Scale#600]
**Describe the bug**
If you have signed into another subscription in the past OR
If you have MFA enabled OR
If you are signed into the Azure portal in your "not default" browser, `Connect-AzAccount` fails to retrieve a token

**Steps to reproduce**

1. Sign into another Azure Subscription and Tenant, sign out
2. Run `Connect-AzAccount`
2. run `get-azcontext `

You will end up in the wrong tenant or your login will fail because no MFA auth will popup. There are lots of forum posts about this issue, it seems to be a PS v5 bug/nuance. 
https://github.com/Azure/azure-powershell/issues/13530

**Resolution**
This script worked for me

```
#Install the AZ Modules
#More info https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-5.8.0
#Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -Verbose
Import-Module Az.Accounts

#Subscription Info
$SubscriptionName = 'Free Trial'
$TenantId = 'my tenant ID'


#Set the correct Az-AD Context
Clear-AzContext
Connect-AzAccount -Tenant $TenantId

#Select a subscription to work with
Select-AzSubscription -Subscription $SubscriptionName
```

**Example Error**
```
PS C:\Windows\system32> Connect-AzAccount -Debug

DEBUG: 12:01:34 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 12:01:37 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 12:01:37 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 12:01:37 PM - Using Autosave scope 'CurrentUser'
DEBUG: 12:01:37 PM - [InteractiveUserAuthenticator] Calling InteractiveBrowserCredential.AuthenticateAsync with TenantId:'', Scopes:'https://management.core.windows.net//.default', AuthorityH
ost:'https://login.microsoftonline.com/', RedirectUri:'http://localhost:8400/'
DEBUG: InteractiveBrowserCredential.Authenticate invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: Request [31a34a14-92b2-4516-9731-4a30a5ea6fdf] POST https://login.microsoftonline.com/organizations/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:31a34a14-92b2-4516-9731-4a30a5ea6fdf
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0-beta.3 (.NET Framework 4.8.4341.0; Microsoft Windows 10.0.19043 )
client assembly: Azure.Identity
DEBUG: Response [31a34a14-92b2-4516-9731-4a30a5ea6fdf] 200 OK (00.7s)
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Cache-Control:no-store, no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
P3P:REDACTED
Set-Cookie:REDACTED
Date:Tue, 01 Jun 2021 02:01:41 GMT
Content-Length:4647

DEBUG: InteractiveBrowserCredential.Authenticate succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-01T03:01:41.0000000+00:00
DEBUG: 12:01:42 PM - [MsalAccessToken] Calling InteractiveBrowserCredential.GetTokenAsync - Scopes:'https://management.core.windows.net//.default'
DEBUG: InteractiveBrowserCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: InteractiveBrowserCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-01T03:01:41.0000000+00:00
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/tenants?api-version=2019-06-01

Headers:
x-ms-client-request-id        : 8704aa4b-4571-4932-a208-934d82d2a853
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-tenant-reads: 11998
x-ms-request-id               : 1d2e5d66-ae1b-493a-a508-f6dec0a619fd
x-ms-correlation-request-id   : 1d2e5d66-ae1b-493a-a508-f6dec0a619fd
x-ms-routing-request-id       : SOUTHEASTASIA:20210601T020143Z:1d2e5d66-ae1b-493a-a508-f6dec0a619fd
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 01 Jun 2021 02:01:42 GMT

Body:
{
  "value": [
    {
      "id": "/tenants/REDACTED",
      "tenantId": "REDACTED",
      "countryCode": "AU",
      "displayName": "Default Directory",
      "domains": [
        "REDACTED"
      ],
      "tenantCategory": "Home"
    }
  ]
}


DEBUG: 12:01:43 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'REDACTED', Scopes:'https://management.core.windows.net//.de
fault', AuthorityHost:'https://login.microsoftonline.com/', UserId:'REDACTED'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: Request [bb056e66-73d3-4d95-b7ec-2667bda3ce52] POST https://login.microsoftonline.com/REDACTED/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:bb056e66-73d3-4d95-b7ec-2667bda3ce52
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0-beta.3 (.NET Framework 4.8.4341.0; Microsoft Windows 10.0.19043 )
client assembly: Azure.Identity
DEBUG: Error response [bb056e66-73d3-4d95-b7ec-2667bda3ce52] 400 Bad Request (01.1s)
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Cache-Control:no-store, no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
P3P:REDACTED
Set-Cookie:REDACTED
Date:Tue, 01 Jun 2021 02:01:43 GMT
Content-Length:644

DEBUG: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  Exception: Azure.Identity.Creden
tialUnavailableException (0x80131500): SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user REDACTED. Ensure that you have authentic
ated with a developer tool that supports Azure single sign on.
WARNING: Unable to acquire token for tenant 'REDACTED' with error 'SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user REDACTED.
. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'
DEBUG: 12:01:46 PM - Unable to acquire token for tenant  #'REDACTED' with error 'Azure.Identity.CredentialUnavailableException: SharedTokenCacheCredential authentica
tion unavailable. Token acquisition failed for user REDACTED. Ensure that you have authenticated with a developer tool that supports Azure single sign on.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.SharedTokenCacheCredential.<GetTokenImplAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.SharedTokenCacheCredential.<GetTokenAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.<GetAccessTokenAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, S
tring promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionNa
me, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)'
WARNING: Unable to set default context 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
Connect-AzAccount : Run Connect-AzAccount to login.
At line:1 char:1
+ Connect-AzAccount -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:12.1143725; Exception - Run Connect-AzAccount to login.;
DEBUG: Finish sending metric.
DEBUG: 12:01:48 PM - ConnectAzureRmAccountCommand end processing.

```

**Comment by hjscherer** [comment]
@simone-bennett is this related to ESLZ or any artifact in this repository that should be updated? If identity has access to multiple tenants it is always recommended to provide tenantId.

**Comment by simone-bennett** [comment]
It was more because there's no way to submit a suggested edit to the doco directly to say "add the tenantid'

There is a note to create any doco updates as issues so I figured I would to save someone else having to look that up and make the deployment as seamless as possible :)


Simone
e: ***@***.******@***.***>
m: 0421 019 967

**Comment by daltondhcp** [comment]
Closing stale issue.
